baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'CloudSight Blog'
theme = 'PaperMod'

[params]
defaultTheme = 'light'
enableSocialSharing = true

[params.homeInfoParams]
Title = 'Hey There! 🤗'
Content = 'Welcome to my blog!'

[[params.socialIcons]]
name = 'email'
url = 'mailto:richaluthra16@gmail.com'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/richaluthra21'

[[params.socialIcons]]
name = 'goodreads'
url = 'https://www.goodreads.com/user/show/181195992-richa-luthra'

[[params.socialIcons]]
name = 'instagram'
url = 'https://www.instagram.com/richa.luthra_/'

[[params.socialIcons]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/richa-luthra21'

[assets]
favicon16x16 = '/assets/favicon-16x16.png'
favicon32x32 = '/assets/favicon-32x32.png'
apple_touch_icon = '/assets/apple-touch-icon.png'

favicon = '/favicon.ico'

[[menu.main]]
identifier = 'home'
name = 'Home'
url = '/'
weight = 10

[[menu.main]]
identifier = 'posts'
name = 'Blog'
url = '/posts/'
weight = 20


