baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'CloudSight Blog'
theme = 'PaperMod'

[params]
defaultTheme = 'dark'

[params.homeInfoParams]
Title = 'Hi there 👋'
Content = 'Welcome to my website.'

[[params.socialIcons]]
name = 'email'
url = 'mailto:richaluthra16@gmail.com'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/richaluthra21'

[[params.socialIcons]]
name = 'goodreads'
url = 'https://www.goodreads.com/user/show/181195992-richa-luthra'

[[params.socialIcons]]
name = 'instagram'
url = 'https://www.instagram.com/richa.luthra_/'

[[params.socialIcons]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/richa-luthra21'
